services:
  rag_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_service
    environment:
      - POSTGRES_URL=postgresql+asyncpg://localhost:5433/postgres
      - AI_MANAGER_URL=http://localhost:8002
      - LOG_LEVEL=info
      - PYTHONPATH=/app
    ports:
      - "8001:8000"
    volumes:
      - rag_service_logs:/app/logs
      - ./forum_knowledge_base:/app/forum_knowledge_base:ro
    networks:
      - ai_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  rag_service_logs:
    driver: local

networks:
  ai_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
